name: Release Builds

on:
  create:
    tags:
      - v*
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build for macOS Intel
        run: cargo build --release --target x86_64-apple-darwin

      - name: Build for macOS ARM
        run: cargo build --release --target aarch64-apple-darwin

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Create release artifacts
        run: |
          mkdir release
          cp target/x86_64-unknown-linux-gnu/release/queso release/queso-linux
          cp target/x86_64-apple-darwin/release/queso release/queso-macos-intel
          cp target/aarch64-apple-darwin/release/queso release/queso-macos-arm
          cp target/x86_64-pc-windows-msvc/release/queso.exe release/queso-windows.exe

      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: release
